### ISSUE TITLE
how to scroll in side menu ?

### ISSUE THREAD

**Issue by spiritelf** [BlackrockDigital/startbootstrap#132]
![11](https://cloud.githubusercontent.com/assets/8556186/18193731/f49e8cb0-7112-11e6-9f69-12544909f6ca.png)

**Comment by spiritelf** [comment]
why?

**Comment by davidtmiller** [comment]
You can open a question on the SB Admin 2 repo here: https://github.com/BlackrockDigital/startbootstrap-sb-admin-2

This is just the repo for the main Start Bootstrap site. :)
