### ISSUE TITLE
How to add reference to ported themes?

### ISSUE THREAD

**Issue by digitalcraftsman** [BlackrockDigital/startbootstrap#136]
Hello together,

I saw that the info page for each theme also references user contributed ports of the themes e.g. to Jekyll and Grav. I ported a few themes (namely Agency, Freelancer and Creative) to [Hugo](http://gohugo.io/).

Since I'm not familiar with the setup of the website (nor Jekyll) it would be great I someone could tell me how to add these references.

Thanks,
Digitalcraftsman

**Comment by davidtmiller** [comment]
You can just email me alternate versions you've created and I can check them out! Just drop me a line at feedback@startbootstrap.com!

**Comment by digitalcraftsman** [comment]
Thanks, I'll do that.
