### ISSUE TITLE
Organization Name

### ISSUE THREAD

**Issue by davidtmiller** [BlackrockDigital/startbootstrap#235]
@dorin1995 I’m reaching out to you on GitHub because it appears you are the owner of the organization named StartBootstrap here on GitHub. I would LOVE it if I could possibly get access to that organization - I’d even be willing to send some money your way for the transfer. I hope you see this issue! Best wishes!

**Comment by davidtmiller** [comment]
@dorin1995 Bumping this to see if you're around. Thanks!

**Comment by davidtmiller** [comment]
@dorin1995 Bumping again, happy new year!

**Comment by davidtmiller** [comment]
@dorin1995

**Comment by davidtmiller** [comment]
@dorin1995

**Comment by MrCyjaneK** [comment]
I'll bump for you @dorin1995

**Comment by davidtmiller** [comment]
Thanks @MrCyjaneK - bumping this again @dorin1995 - if you're out there, please respond!

**Comment by davidtmiller** [comment]
@dorin1995 Bump, if you're out there let's talk!

**Comment by davidtmiller** [comment]
@dorin1995 Another bump - looking for you!

**Comment by davidtmiller** [comment]
Finally solved!
