### ISSUE TITLE
Can anyone upload ready to use theme ?

### ISSUE THREAD

**Issue by dardandemiri** [BlackrockDigital/startbootstrap#244]
Was just wondering if it is possible to upload themes that random users create. 
And if yes what are the steps?

**Comment by davidtmiller** [comment]
I don't support user submitted themes for a few reasons. Mainly, I want to make sure that the themes remain up to date with the latest version of Bootstrap, bug free in latest versions of modern browsers, and free from any sort of malicious code.

By keeping everything in-house, I can maintain a quality standard for my themes, and make sure they are safe to use. Hopefully this helps answer your question!
