### ISSUE TITLE
SB Admin V2 : full height sidebar and page-wrapper

### ISSUE THREAD

**Issue by Err0r404** [BlackrockDigital/startbootstrap#36]
Hi,

Is it possible to make SB Admin V2 usign full window's height ?

I mean having a full height sidebar and full height page-wrapper even is both of them are empty and no unnecessary scrollbar.

Thanks !

**Comment by pheivip** [comment]
I have the same problem.

I have changed html and body to have height: 100%;

Also my #wrapper has height: 100%; verified with browser tools in chrome.
The #page-wrapper has min-height: 100%;
But the #page-wrapper div does not fill up its parent content

	<!DOCTYPE html>
	<html>
	<head>

		<meta name="layout" content="main"/>

		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

	</head>

	<body>

	<div id="wrapper" class="fill">

		<div id="page-wrapper"></div>

	</div>

	</body>
	</html>

	.fill {
		min-height: 100% !important;
	}

**Comment by davidtmiller** [comment]
I will look into this with the next release, thanks!

**Comment by AdamHTML7** [comment]
You can change this maually like startbootstrap said by using the #page-wrapper css code.

**Comment by AdamHTML7** [comment]
If you want a minified version, go to http://adamlower.com/bootscdn
