### ISSUE TITLE
SB Admin 2 - scroling bug?

### ISSUE THREAD

**Issue by simonfranz** [BlackrockDigital/startbootstrap#39]
I think the blank page has some errors for pages with small content.
For example at the blank page (http://startbootstrap.com/templates/sb-admin-v2/blank.html) there is a scrollbar although the scrollbar isn't needed. It would be great if you could look into this.

**Comment by tmthyjames** [comment]
The answer didn't work for me so I used:

```
.sidebar{
    overflow-y: scroll;
    position: fixed;
}
```

Then:

```
var topNavBar = 50;
var footer = 48;
var height = $(window).height();
$('.sidebar').css('height', (height - (topNavBar+footer)));

$(window).resize(function(){
    var height = $(window).height();
    $('.sidebar').css('height', (height - (topNavBar+footer)));
});
```

If you don't have a top navbar or footer, then just remove those.
