### ISSUE TITLE
Fixed / Floated Vertical menu on SB Admin 2

### ISSUE THREAD

**Issue by teknosains** [BlackrockDigital/startbootstrap#46]
I found that  http://startbootstrap.com/templates/sb-admin-v2/  vertical menu bar on the left is not Fixed / Floated ( when scroll event on long content )

Will it be added ? I think its cool

or its configurable by default like adding  navbar-fixed  etc ? 

Thanks

**Comment by eeezyy** [comment]
@salem-san nice solution, but in the mobile view the menu will get in your way.

**Comment by h-stivalet** [comment]
@eeezyy add the 4th line

    .navbar-default{
        position: fixed;
        width: 100%;
        margin: 0 0 405px 0;
        padding-top: 101px;
    }

**Comment by vcleapz** [comment]
Just put `<p style="margin: 35px;"></p>` after `<body>`. And gotcha! you will see fixed navbar without any problem again!

**Comment by ezequielzeroc** [comment]
add a z-index to see the navigation bar at the top of all layers

.navbar-default{
    position: fixed;
    z-index: 999;
    width: 100%;
    margin: 0 0 405px 0;
}

**Comment by kumarmrigank1** [comment]
i do not want sidenav bar to be fixed on mobile view mode can any one help ?
