### ISSUE TITLE
Show vertical scrollbar when side bar has many items

### ISSUE THREAD

**Issue by kyriakos77** [BlackrockDigital/startbootstrap#60]
In sb-admin-v2, when the sidebar has more items that can fit in the page's height, no vertical scrollbar is displayed. Instead the excess items are being lost.

Any way around this?

**Comment by tmthyjames** [comment]
Just tested this and putting it here for anyone still interested.

```
.sidebar{
    overflow-y: scroll;
    position: fixed;
}
```

Then:

```
var topNavBar = 50;
var footer = 48;
var height = $(window).height();
$('.sidebar').css('height', (height - (topNavBar+footer)));

$(window).resize(function(){
    var height = $(window).height();
    $('.sidebar').css('height', (height - (topNavBar+footer)));
});
```

If you don't have a top navbar or footer, then just remove those.

**Comment by cacpmw** [comment]
@kyriakos77 what file did you add that in? I have the same problem but with sbadmin 1. I need to add a scrollbar to the menu but I cant find that class anywhere

**Comment by nicolaspluhator** [comment]
@cacpmw 

Add the following to your css/scss:

`.navbar-sidenav {
  overflow:hidden;
}`

This will add a hidden scrollbar to the sidenav. Adding a visible scrollbar throws off the tooltips when the sidenav is collapsed. I could not solve that part but would prefer the scrollbar to be visible if someone else has a solution.

**Comment by shravanm05** [comment]
You can add vertical scroll bar by adding this 


```
    $(".button-collapse").sideNav();
    var el = document.querySelector('.custom-scrollbar');
    Ps.initialize(el);
```
