### ISSUE TITLE
sb admin 2v: the issue of side bar show all hidden collapse when "page-wrapper" been deleted

### ISSUE THREAD

**Issue by wangdu1005** [BlackrockDigital/startbootstrap#74]
Hello, I love your templates, but I got some problem with the side bar issues, could you give me a solution?

When I delete the page-wrapper content (index.html), the side-bar show all its hidden collapses, and it do not let me hide it back...I check chrome console, it shows "Uncaught ReferenceError: Morris is not defined". So, I comment all Morris links, and it didn't show error, also the collapses work fine now!

Why this issue will happen in this situation?

**Comment by muratkurtun** [comment]
hi,
can u share js file?
thanks.
