### ISSUE TITLE
Problem Solved

### ISSUE THREAD

**Issue by AdamHTML7** [BlackrockDigital/startbootstrap#99]
I have seen many people complaining about the file sizes being to big so I created a solution: Simple SB. It started about a week ago, and I have converted 2 templates already! What is allows you to do is copy and paste two lines of code and delete the CSS and JS directories. It makes the loading time a bit quicker, and is very useful. Look at my repositories labelled with SimpleSB-... 
I give all the credit to Start Bootstrap.

**Comment by davidtmiller** [comment]
Hey thanks! I see you set up a CDN for some of the files. I actually have a MaxCDN account and I am in the works of setting up some large scale CDN's for all of the basic core CSS and JS files that are used within Start Bootstrap. I've actually used them once (as a test) in the Freelancer Jekyll build - you can see it in action here: https://github.com/BlackrockDigital/startbootstrap-freelancer-jekyll/blob/gh-pages/_includes/head.html check out the CSS being served up in the head tag!

**Comment by AdamHTML7** [comment]
Oh that's cool! I tried to setup a CDN for it but eventually the files got corrupted from too much moving them around from place to place. ;-( That is neat that your doing it too!
